logLevel: info
api: yes
apiAddress: :9997
rtsp: yes
rtspAddress: :8554
webrtc: yes
webrtcAddress: :8889
webrtcAllowOrigins: ["*"]
webrtcLocalUDPAddress: :8189
hls: no
pathDefaults:
  rtspTransport: tcp
  sourceOnDemand: yes
  sourceOnDemandStartTimeout: 12s
  sourceOnDemandCloseAfter: 10s
paths: {}
